messages/urls.py
from django.conf.urls import url
from django.urls import re_path

from . import views

app_name = "messages"

urlpatterns = [
    re_path(r'^$', views.index, name="index"),
    re_path(r'^(?P<message_id>\d+)/$', views.detail, name='detail'),
    re_path(r'signup', views.signup, name='signup')
]

myservice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path, re_path

from messages.views import index

urlpatterns = [
    path(r'', index),
    re_path(r'^messages/', include("messages.urls")),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messages/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    pub_date = models.DateTimeField('date published', default=datetime.now)
    image = models.ImageField(upload_to='images', null=True, blank=True)

messages/forms.py
from django import forms
from django.forms import ModelForm

from .models import Message


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ["text", "image"]

messages/views.py
from datetime import datetime, timedelta

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

from .forms import MessageForm
from .models import Message

# Create your views here.
from .service import MessageService


def index(request):
    user = request.user
    if not user.is_authenticated:
        return redirect(reverse('login'))

    if request.method == "POST":
        # save new message, user_id - current_user
        form = MessageForm(request.POST, request.FILES)
        if form.is_valid():
            new_message = form.save(commit=False)
            new_message.user_id = user.id
            new_message.save()
        return redirect("messages:index")

    order_by = request.GET.get('order', '-pub_date')
    filters = {}
    last_24_hours = request.GET.get('last_24_hours', False) == 'true'
    if last_24_hours:
        filters['date_from'] = datetime.now() - timedelta(days=1)
    user_id = request.GET.get('user_id')
    if user_id:
        filters['user_id'] = user_id

    message_service = MessageService()
    messages = message_service.get_messages(
        order_by=order_by,
        **filters
    )

    return render(
        request,
        "index.html",
        {
            "form": MessageForm,
            "latest_messages": messages,
            "order_by": order_by,
            "last_24_hours": last_24_hours,
            "users": User.objects.all(),
            "selected_user": user_id,
        }
    )


def detail(request, message_id):
    return render(request, "detail.html", {"message": get_object_or_404(Message, pk=message_id)})


def message(request, message_id):
    messages = get_object_or_404(Message, pk=message_id)
    try:
        user = messages.user.get(pk=request.POST['user'])
    except (KeyError, User.DoesNotExist):
        return render(request, 'detail.html', {'message': message, 'error_message': "Message does not exist"})
    else:
        if user.correct:
            return render(request, "index.html", {"latest_messages": Message.text.order_by('-pub_date')[:5],
                                                  "message": "Nice! Choose another one!"})
        else:
            return render(request, 'answer.html', {'message': message(), 'error_message': 'Wrong Answer!'})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('messages:index')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

messages/templates/base.html
{% load static %}
{% load tz %}

<html lang="ua">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}"/>
    <title>Messages system</title>
</head>
{% timezone "Europe/Kiev" %}
<body>
    <div class="header">
      <a href="{% url 'messages:index'  %}" class="logo">Messages System</a>
      <div class="header-right">
        {% if user.is_authenticated %}
            <span>Hello, {{ user.username }}</span>
            <span>|</span>
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'messages:signup' %}">Sign up</a>
        {% endif %}
      </div>
    </div>
    {% block content %}
    {% endblock %}
{% endtimezone %}
</body>

</html>

messages/templates/detail.html
{% extends "base.html" %}

{% block content %}
    <br><small>
        Published at: {{ message.pub_date }}
        Author: {{ message.user.username }}
    </small>
    <p>{{ message.text }}</p>
    {% if message.image %}<img src="/media/{{ message.image }}" alt="Image">{% endif %}
{% endblock %}

messages/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>List of Messages</h1>

    {% if message %}
        <p><strong>{{ message }}</strong></p>
    {% endif %}

    {% if order_by == "-pub_date" %}
        <a
                class="button"
                href="/messages/?order=pub_date&last_24_hours=
{% if last_24_hours%}true{% else %}false{% endif %}
{% if selected_user %}&user_id={{selected_user}}{% endif %}"
        >
            Order by pub date
        </a>
    {% else %}
        <a
                class="button"
                href="/messages/?order=-pub_date&last_24_hours=
{% if last_24_hours%}true{% else %}false{% endif %}
{% if selected_user %}&user_id={{selected_user}}{% endif %}"
        >
            Order by
            pub date
            desc
        </a>
    {% endif %}

    {% if last_24_hours %}
        <a class="filter" href="/messages/">Clear filter</a>
    {% else %}
        <a
                class="filter"
                href="/messages/?last_24_hours=true&?order_by={{order_by}}
{% if selected_user %}&user_id={{selected_user}}{% endif %}"
        >
            Messages
            published in
            last 24
            hours
        </a>
    {% endif %}
    <select class="filter" name="user-filter" id="user-filter"
            onchange="document.location=document.location.origin+document.location.pathname+'?user_id='+this
            .options[this.selectedIndex].value">
        <option value="" {% if selected_user is None %}selected{% endif %}>User not selected</option>
        {% for user in users %}
            <option value="{{ user.id }}" {% if selected_user == user.id|slugify %}selected{% endif %}>
                {{ user.username }}
            </option>
        {% endfor %}
    </select>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br><button class="publish" type="submit">Publish</button>
    </form>

    {% if latest_messages %}
        <ul>
            {% for messages in latest_messages %}
                <li>
                    <a href="/messages/{{ messages.id }}/">
                        {{ messages.text }} <small>{{ messages.pub_date }} | {{ messages.user.username }}</small>
                    </a>
                </li>
                {% if messages.image %}
                    <img src="/media/{{messages.image}}" alt="Image">
                {% endif %}
            {% endfor %}
        </ul>

    {% else %}
        <p>You have no available messages</p>
    {% endif %}
{% endblock %}

messages/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}